version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/web/*"
    schedule:
      interval: "daily"
    groups:
      patch-updates:
        update-types: [ "patch" ]
      minor-updates:
        update-types: [ "minor" ]
      major-updates:
        update-types: [ "major" ]
    assignees:
      - "james-d12"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "james-d12"
