name: Build and Scan NixOS Server Config
permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-server:
    name: Build and Scan NixOS Server Config
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3

      - name: Install Syft
        run: curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -dd -b /usr/local/bin

      - name: Check Flake
        run: nix flake check
        working-directory: ./server/config

      - name: Build Server
        id: build
        run: nix build .#nixosConfigurations.vps.config.system.build.toplevel --print-out-paths
        working-directory: ./server/config

      - name: Run Syft Scan
        run: |
          RESULT_PATH=$(readlink -f result)
          echo "Scanning resolved store path: $RESULT_PATH"
          syft scan dir:$RESULT_PATH -v -o json > syft-output.json
        working-directory: ./server/config

      - name: Upload SBOM
        uses: actions/upload-artifact@v6
        with:
          name: syft-sbom
          path: ./server/config/syft-output.json
