name: Build & Deploy St Catherine's Group Website
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'web/sites/stcatherinesgroup.com/**'
      - 'web/package.json'
      - 'web/pnpm-lock.yaml'
      - 'web/pnpm-workspace.yaml'
      - 'web/libs/**'
      - '.github/workflows/web-stcatherinesgroup.yml'
      - '.github/workflows/site-template.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stcatherinesgroup:
    name: "Build & Deploy St Catherine's Group"
    uses: ./.github/workflows/site-template.yml
    with:
      site: stcatherinesgroup.com
    secrets:
      server_host: ${{ secrets.VPS_HOST }}
      server_ssh_port: ${{ secrets.VPS_PORT }}
      server_key: ${{ secrets.VPS_CI_KEY }}
      server_key_password: ${{ secrets.VPS_CI_KEY_PASSWORD }}