name: Build & Deploy Black Cat Tattoos Website
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'web/sites/blackcattattoos.co.uk/**'
      - 'web/package.json'
      - 'web/pnpm-lock.yaml'
      - 'web/pnpm-workspace.yaml'
      - 'web/libs/**'
      - '.github/workflows/web-blackcattattoos.yml'
      - '.github/workflows/site-template.yml'

jobs:
  blackcattattoos:
    name: "Build & Deploy Black Cat Tattoos"
    uses: ./.github/workflows/site-template.yml
    with:
      site: blackcattattoos.co.uk
    secrets:
      server_host: ${{ secrets.VPS_HOST }}
      server_ssh_port: ${{ secrets.VPS_PORT }}
      server_key: ${{ secrets.VPS_CI_KEY }}
      server_key_password: ${{ secrets.VPS_CI_KEY_PASSWORD }}
