name: Build & Deploy Reroof and Build Surrey Website
permissions:
  contents: read

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - 'web/sites/reroofandbuildsurrey.com/**'
      - 'web/package.json'
      - 'web/pnpm-lock.yaml'
      - 'web/pnpm-workspace.yaml'
      - 'web/libs/**'
      - '.github/workflows/web-reroofandbuildsurrey.yml'
      - '.github/workflows/site-template-v2.yml'

jobs:
  blackcattattoos:
    name: "Build & Deploy Reroof and Build Surrey"
    uses: ./.github/workflows/site-template-v2.yml
    with:
      site: reroofandbuildsurrey.com
    secrets:
      server_host: ${{ secrets.VPS_HOST }}
      server_ssh_port: ${{ secrets.VPS_PORT }}
      server_key: ${{ secrets.VPS_CI_KEY }}
      server_key_password: ${{ secrets.VPS_CI_KEY_PASSWORD }}
